### ISSUE TITLE
pickle.load ran out of input at dataset.py

### ISSUE THREAD

**Issue by Yi-Hsuan-Su** [Colin97/Point2Mesh#4]
pickle.load ran out of input during training. Did I do something wrong？

**Comment by Colin97** [comment]
Could you provide the error message and the memory size of your machine?

**Comment by Yi-Hsuan-Su** [comment]
It seems that some of the dataset size is empty then result in pickle.load turn out to be error. How can I fixed it?
![image](https://user-images.githubusercontent.com/40382478/100302515-7c9aee80-2fd5-11eb-813d-ee2eaa626ec3.png)

**Comment by Colin97** [comment]
This could be a mistake when i finally organizing the data, i have already update the data. Could you please try again？

**Comment by Yi-Hsuan-Su** [comment]
![image](https://user-images.githubusercontent.com/40382478/100609736-74321300-3349-11eb-9130-a571ac2e0406.png)
hello 
Seems that the problem still remain!

**Comment by Yi-Hsuan-Su** [comment]
![image](https://user-images.githubusercontent.com/40382478/100701156-02ee7080-33da-11eb-8ba2-a33574436131.png)
I'm not really sure why the problem still exist. The file size is correct this time...

**Comment by Colin97** [comment]
Sorry, it seems that 7084db*.p is still incomplete. You can download this single pickle file (updated) from the attachment.

I have checked that all the pickle files should be able to load from my end this time. Please feel free to let me know if the problem still exists. I will update the dataset file later (only change one file).

[7084db2193bc9ee43d113b8340bd5029.p.zip](https://github.com/Colin97/Point2Mesh/files/5620686/7084db2193bc9ee43d113b8340bd5029.p.zip)

**Comment by Yi-Hsuan-Su** [comment]
It happens to be successful since I changed the file 7084db*.p only. I'll keep aware if there is other problem. Thank you.
